import { supabase } from "../lib/supabase.js";

// The app keeps order items inline on the order object; the DB splits them
// into orders + order_items. This service joins them back together so the
// UI shape ({ items: [{ name, variant, qty, price }] }) stays unchanged.
// order_number is generated by the DB ('BT-' || sequence) — collision-safe,
// unlike the old localStorage counter.

const SELECT = "*, order_items(name, variant, qty, unit_price)";

function fromRow(row) {
  return {
    id: row.id,
    orderNumber: row.order_number,
    customerName: row.customer_name,
    phone: row.phone,
    address: row.address || "",
    note: row.note || "",
    items: (row.order_items || []).map((item) => ({
      name: item.name,
      variant: item.variant ?? null,
      qty: item.qty,
      price: item.unit_price,
    })),
    total: row.total,
    status: row.status,
    createdAt: row.created_at,
  };
}

export async function getOrders() {
  const { data, error } = await supabase
    .from("orders")
    .select(SELECT)
    .order("created_at", { ascending: false });
  if (error) throw new Error(error.message);
  return data.map(fromRow);
}

export async function updateOrderStatus(id, status) {
  const { data: updated, error } = await supabase
    .from("orders")
    .update({ status })
    .eq("id", id)
    .select(SELECT)
    .maybeSingle();
  if (error) throw new Error(error.message);
  if (!updated) throw new Error("Sifariş tapılmadı");
  return fromRow(updated);
}

// Checkout runs through the place_order() database function (see
// supabase/auth-rls-migration.sql): it upserts the customer by phone and
// creates the order + items in one transaction, and is the only write path
// the anon storefront has into the orders tables.
export async function createOrder(data) {
  const { data: order, error } = await supabase.rpc("place_order", {
    p_customer_name: data.customerName,
    p_phone: data.phone,
    p_address: data.address || null,
    p_note: data.note || null,
    p_total: data.total,
    p_items: (data.items || []).map((item) => ({
      name: item.name,
      variant: item.variant || null,
      qty: item.qty,
      price: item.price,
    })),
  });
  if (error) throw new Error(error.message);
  return fromRow(order);
}
